### Relevant Python modules: Numpy

Start this exercise notebook during the tutorial session, you can complete it as homework.

Please also see the [online Numpy resources](https://numpy.org/learn/).

Installation: 

```bash
pip install numpy
```

In [2]:
# check that your kernel 'knows' numpy

import numpy as np

In [6]:
import numpy as np

#### Create an array consisting of 2 rows and 5 columns, containing with the first 10 integers

In [18]:
my_array = np.arange(10)

reshaped_array = my_array.reshape(2,5)

reshaped_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Use the appropriate methods to print out the shape of the array and the total number of elements

In [19]:
print(reshaped_array.shape)

(2, 5)


In [20]:
print(reshaped_array.size)

10


##### What's the sum of the values in each row?

In [21]:
# remember to set the axis parameter
print(reshaped_array.sum(axis=1))


[10 35]


##### Generate a 3x3 unit/identity matrix:

$$
U_{3\times 3}  =  
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
$$

In [23]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Generate a 2x3 matrix with values sampled from a standard normal distribution

Have a look at the [online documentation](https://numpy.org/doc/stable/reference/random/index.html). 

In [25]:
# look at the np.random documentation to sample data  
random_matrix = np.random.normal(0,1,(2,3))
random_matrix

array([[-1.25854672, -1.82248164,  0.75945552],
       [-0.21832405, -0.78542951, -0.66847843]])