### Relevant Python modules: Numpy

Start this exercise notebook during the tutorial session, you can complete it as homework.

Please also see the [online Numpy resources](https://numpy.org/learn/).

Installation: 

```bash
pip install numpy
```

In [4]:
# check that your kernel 'knows' numpy

import numpy as np

In [6]:
import numpy as np

#### Create an array consisting of 2 rows and 5 columns, containing with the first 10 integers

In [17]:
my_array = np.arange(10)

resized_array = my_array.reshape(2,5)


my_array
resized_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Use the appropriate methods to print out the shape of the array and the total number of elements

In [18]:
resized_array.shape


(2, 5)

In [19]:
resized_array.size

10

##### What's the sum of the values in each row?

In [22]:
# remember to set the axis parameter

resized_array.sum(axis = 1)

array([10, 35])

##### Generate a 3x3 unit/identity matrix:

$$
U_{3\times 3}  =  
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
$$

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Generate a 2x3 matrix with values sampled from a standard normal distribution

Have a look at the [online documentation](https://numpy.org/doc/stable/reference/random/index.html). 

In [25]:
# look at the np.random documentation to sample data  
random_matrix = np.random.normal(0,1,6)
random_matrix.reshape(2,3)

array([[-0.12460765, -0.87836327,  0.55442842],
       [-0.06195666,  0.71725542, -0.01829717]])